import "./globals.css";
import localFont from "next/font/local";
import Providers from "./providers";
import type { Metadata } from "next";
//import type으로 next 패키지에서 제공하는 Metadata타입을 가져와서 명시적으로 타입을 붙여줌

interface RootLayoutProps {
  children: React.ReactNode;
}

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Panda Market",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="flex min-h-screen flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
