import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header.jsx";
import Container from "@/components/common/Container.jsx";
import Footer from "@/components/common/Footer.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pretendard = localFont({
  src: "../asset/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const ROKAFSans = localFont({
  src: "../asset/fonts/ROKAFSans.woff2",
  display: "swap",
  variable: "--font-rokaf-sans",
});

export const metadata = {
  title: "판다마켓",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} ${pretendard.variable} ${ROKAFSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {" "}
        <Header />
        <Container className="flex-1">{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
