import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const rokafSans = localFont({
  src: [
    {
      path: "../assets/fonts/ROKAF_Sans_Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/ROKAF_Sans_Medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-rokaf-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${rokafSans.variable}`}>
      <body className="min-h-screen flex flex-col">
        <Header />
        <div className="flex-1 pt-17.5">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
